version: '3'
services:
  chrome97:
    image: selenoid/vnc_chrome:97.0
    container_name: chrome
    privileged: true
    shm_size: '2g'
    tty: true
    command: ["-limit", "${MAXINSTANCES}", "-mem", "1g", "-cpu", "1g", "-session-delete-timeout", "3m", "-timeout", "2m"]
    ports:
      - "4444:4444"
    volumes:
    - ${PWD}/tests/UI/pdfs/data/actual/:/var/lib/actual/
